# Generated by Django 2.2.3 on 2019-08-14 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20190815_0017'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ('-created_date',), 'verbose_name': 'Makale', 'verbose_name_plural': 'Makaleler'},
        ),
        migrations.RemoveField(
            model_name='article',
            name='author',
        ),
        migrations.AddField(
            model_name='article',
            name='article_kategori',
            field=models.CharField(choices=[('ishukuku', 'İş Hukuku'), ('icrahukuku', 'İcra Hukuku')], default='ishukuku', max_length=50, verbose_name='Makale Kategorisi'),
        ),
        migrations.AddField(
            model_name='article',
            name='article_meta_description',
            field=models.CharField(default='default meta acıklaması', max_length=250, verbose_name='Makale Meta Açıklaması'),
        ),
        migrations.AddField(
            model_name='article',
            name='article_slug',
            field=models.SlugField(default='defaultVal', unique=True),
        ),
    ]
